version: '3.8'

services:
  callbook-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: callbook-front-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4200
    restart: unless-stopped
    networks:
      - callbook-network

networks:
  callbook-network:
    driver: bridge