name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ec2-deploy  # Add this line to specify the environment name

    steps:
      # Step 1 - Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - Debug secrets (remove after fixing)
      - name: Debug secrets
        run: |
          echo "EC2_HOST length: ${#EC2_HOST}"
          echo "EC2_USER length: ${#EC2_USER}"
          echo "EC2_SSH_KEY length: ${#EC2_SSH_KEY}"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      # Step 3 - Setup SSH Agent
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 4 - Deploy to EC2
      - name: Deploy Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to frontend repo
            cd /apps/callbook-proxy/callbook-front

            # Ensure repo is on main branch and up to date
            git fetch origin
            git checkout main
            git reset --hard origin/main

            # Go back to parent folder for docker-compose
            cd ..

            # Rebuild and restart only the frontend service
            docker compose build frontend
            docker compose up -d frontend
          EOF
